### ISSUE TITLE
Import function signatures, structs and types from .c file

### ISSUE THREAD

**Issue by simonlindholm** [matt-kempster/mips_to_c#10]
It would be neat if you could run `main.py file.s index file.c`, where `file.c` is the file we're trying to decompile into, and the decompiler would use that file (and its includes) to construct a function signature for the function we're decompiling, convert struct member accesses into reasonably named things, determine how many parameters to pass to functions, etc.

**Comment by matt-kempster** [comment]
Even a manually-curated list of structs that could be passed in as a separate argument to `main.py` would be good for this. (Recursively checking `#include`s sounds a little painful.)

**Comment by simonlindholm** [comment]
Yeah, implementing a pre-processor would be painful, but it might work to require the user to do `main.py file.s index <(cpp file.c)`. For structs/function I think you could get far with hand-written heuristic string parsing. (And some logic to handle typedefs and alignment/padding.)
