### ISSUE TITLE
Support LD instruction

### ISSUE THREAD

**Issue by TGEnigma** [matt-kempster/mips_to_c#148]
The decompiler currently does not support the LD instruction used for 64 bit loads.

**Comment by simonlindholm** [comment]
Added the instruction. Beware though that mips_to_c is generally quite bad at handling 64-bit numbers (it hasn't really been needed so far), and pointers are assumed to be 32-bit.

**Comment by TGEnigma** [comment]
Thanks a lot for your swift response. My usecase involves decompiling PS2 code, so fortunately I don't need 64-bit pointers.
