### ISSUE TITLE
Support JALR and BREAK opcodes

### ISSUE THREAD

**Issue by MNGoldenEagle** [matt-kempster/mips_to_c#44]
Add support for parsing JALR and BREAK opcodes.  JALR can be interpreted as:

`jalr $ra, $v0` becomes `(*v0)(arglist...);`
BREAK can either be interpreted as dropping the node it's in (assuming that it's a compiler check that was inlined, such as checking for integer overflow), or as calling a function called throw(break_value) that simply acts as a placeholder for the break logic.

**Comment by simonlindholm** [comment]
This should have worked to some extent already, but not the two-argument form of `jalr` with explicit `$ra`, and `break` only in the specific form of division that IDO emits.

Fixed the former in 0a2aeecd2fe8e380c006f568b9220ba20e8e914f, anyhow, and edbd5a9c132d9822a7fad9622683604b97f5598b should improve the latter. (Dropping the whole node is an interesting idea... We don't have an easy way of doing that right now, but it might be worth doing as a replacement for our current fragile division error checking setup.)
