### ISSUE TITLE
Support `j` instruction

### ISSUE THREAD

**Issue by simonlindholm** [matt-kempster/mips_to_c#47]
It can be either a tail call (replace by `jalr`, `jr $ra`, `nop`) or a branch within the same function (replace by `b`). Currently we fail with a cryptic assertion error (`assert jump.is_branch_instruction()` in the middle of flow_graph.py).

**Comment by isovector** [comment]
What should happen in this case? Emit a label and a goto in the C?

**Comment by simonlindholm** [comment]
This issue is a bit outdated -- Ethan recently added support for `j` in #85, #86, #87 that treats it the same as `b`, which in turn behaves the same as a fallthrough into another basic block (both are BasicNode's). GCC apparently emits `j` instead of `b`, so treating them the same makes sense. There might be more circumstances in which `j` can come up as speculated about in the issue comment, but let's take those as separate issues and not future-proof things without real examples.
