### ISSUE TITLE
Handle conditionally set registers

### ISSUE THREAD

**Issue by simonlindholm** [matt-kempster/mips_to_c#9]
Here's the plan I'm thinking of:
- for each block, mark which registers get written in that block
- for each register `reg`, and for every block node `n`: we need to construct a value for `n.regs[reg]`, either as a direct copy from another `RegInfo`, or as a phi node, in SSA parlance. Obviously, if this node has just one predecessor this is simple, but in the general case it's more tricky. So we do the following:
  * compute whether there exists a node `m` such that all paths backwards from `n`, stopping at `m`, never reach any nodes that set `reg`
  * for these purposes, treat the entry node as setting all registers
  * there is bound to be some DFS-based algorithm for computing this in O(n), but the cheating way is to loop over all `m` and try them one by one. O(n^3 * regs) is hopefully fine... (one could get rid of the `regs` factor using bitsets, I believe)
  * if there is such an `m`, pick one arbitrarily and copy `m.regs[reg]` from there
  * given that we add an initial pass that throws away all unreachable nodes, these copies can never become cyclic. If they did, that would mean that *all* paths backwards from this cycle (not stopping anywhere) never set `reg`, but from some part of the cycle we must be able to reach the entry node, which does set `reg`, contradiction. This argument works even if we consider different registers at the same time.
  * this means that we can compute an order in which to emit the nodes, acyclically, so that we can do direct `m.regs[reg]` copies when we want to
  * if there is no such `m`, set `n.regs[reg]` to contain a PhiExpr, and emit a set to that phi variable at the end of all the predecessors. This PhiExpr should work like a EvalOnceExpr, only emitting the phi variable and associated sets, and only marking the associated sets as a read, once it's `mark_used`.

The `if_statements` code might already be doing some of these steps, I'm not sure.

**Comment by matt-kempster** [comment]
#21 finishes the bulk of this up.
