### ISSUE TITLE
Recognise magic division

### ISSUE THREAD

**Issue by nanaian** [matt-kempster/mips_to_c#90]
See https://github.com/NationalSecurityAgency/ghidra/issues/668.

Currently mips to c outputs `(MULT_HI(temp_v0, 0x51EB851F) >> 5) - (temp_v0 >> 0x1F)` for source `temp_v0 * 1/100` (I think).

**Comment by zbanks** [comment]
Mostly fixed by #164. Handles ~80% of the cases in PM, other ones are too hard to simplify for now (e.g. the expressions involve phis or stack variables).
